[package]
name = "walrus-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walrus = "0.20.1"
anyhow = "1.0.75"
env_logger = "0.10.0"